import React, { useState, useEffect } from 'react';
import { db } from '../../../config/firebase';
import { collection, query, onSnapshot, deleteDoc, doc } from 'firebase/firestore';
import { Link, Trash2, Copy, Check, Loader2 } from 'lucide-react';

const InvitesPanel = ({ workspace }) => {
  const [invites, setInvites] = useState([]);
  const [loading, setLoading] = useState(true);
  const [copiedId, setCopiedId] = useState(null);

  useEffect(() => {
    if (!workspace?._id) return;
    const q = query(collection(db, 'workspaces', workspace._id, 'invites'));
    const unsubscribe = onSnapshot(q, (snapshot) => {
      const data = snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));
      setInvites(data);
      setLoading(false);
    });
    return () => unsubscribe();
  }, [workspace]);

  const handleRevokeInvite = async (id) => {
    if (!workspace?._id || !id) return;
    try {
      await deleteDoc(doc(db, 'workspaces', workspace._id, 'invites', id));
    } catch (err) {
      console.error(err);
    }
  };

  const copyCode = (id, code) => {
    const url = `${window.location.origin}/invite/${code}`;
    navigator.clipboard.writeText(url);
    setCopiedId(id);
    setTimeout(() => setCopiedId(null), 2000);
  };

  return (
    <div className="space-y-8 max-w-3xl mx-auto">
      <div>
        <h2 className="text-2xl font-bold text-white mb-1">Active Invite Links</h2>
        <p className="text-slate-400 text-sm">View and manage all active invitation links generated by workspace members.</p>
      </div>

      <div className="bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-xl">
        <div className="p-4 border-b border-slate-800 bg-slate-900/50 flex items-center justify-between">
          <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider px-2">Invites ({invites.length})</h3>
        </div>

        {loading ? (
          <div className="flex justify-center p-8"><Loader2 className="w-6 h-6 animate-spin text-slate-500" /></div>
        ) : invites.length === 0 ? (
          <div className="p-8 text-center text-slate-500 text-sm">No active invite links found. Generate one from the workspace header!</div>
        ) : (
          <div className="divide-y divide-slate-800">
            {invites.map((inv) => (
              <div key={inv.id} className="p-6 flex items-center justify-between gap-4 hover:bg-slate-800/30 transition-all">
                <div className="flex items-center gap-4 min-w-0">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20 shrink-0">
                    <Link className="w-5 h-5 text-emerald-400" />
                  </div>
                  <div className="min-w-0">
                    <h4 className="text-sm font-bold text-white truncate font-mono">{inv.code}</h4>
                    <p className="text-xs text-slate-500 truncate mt-0.5">Created: {inv.createdAt?.toDate ? inv.createdAt.toDate().toLocaleDateString() : 'Recently'} • Uses: {inv.uses || 0}</p>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <button 
                    onClick={() => copyCode(inv.id, inv.code)}
                    className="p-2 bg-slate-800 hover:bg-slate-700 text-slate-300 rounded-xl transition-all flex items-center gap-1.5 text-xs font-semibold"
                  >
                    {copiedId === inv.id ? <><Check className="w-4 h-4 text-emerald-400" /> Copied</> : <><Copy className="w-4 h-4" /> Copy Link</>}
                  </button>
                  <button 
                    onClick={() => handleRevokeInvite(inv.id)}
                    className="p-2 text-rose-500 hover:bg-rose-500/10 rounded-xl transition-all border border-rose-500/20"
                    title="Revoke Invite"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default InvitesPanel;
